# Generated by Django 3.2.4 on 2021-08-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
