# Generated by Django 3.2.4 on 2021-08-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20210825_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='totalDislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='totalLikes',
        ),
        migrations.AddField(
            model_name='post',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
