# Generated by Django 3.2.4 on 2021-08-31 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedBy',
            field=models.ManyToManyField(related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loggedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
