# Generated by Django 3.2.4 on 2021-09-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20210831_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isLiked',
        ),
    ]
