# Generated by Django 3.2.4 on 2021-09-02 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20210902_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedBy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
