# Generated by Django 3.2.4 on 2021-09-10 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=datetime.datetime(2021, 9, 10, 8, 31, 29, 351829, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
