# Generated by Django 3.2.4 on 2021-09-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_alter_comment_commenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePic',
        ),
    ]
