# Generated by Django 3.2.4 on 2021-09-14 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_auto_20210913_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='originalPoster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
