# Generated by Django 3.2.4 on 2021-09-14 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_alter_post_originalposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='originalPoster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
