# Generated by Django 3.2.4 on 2021-09-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_alter_post_originalposter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
